---
- name: Converge
  hosts: all
  tasks:
  - name: 'ensure necessary packages are installed'
    apt:
      name: '{{ item }}'
      update_cache: true
    loop:
    - gpg-agent
    - bash-completion
    - procps
  - name: 'Include container-runtime'
    include_role:
      name: 'container-runtime'
