---

# Defaults for ContainerD
containerd_package: 'containerd.io'
containerd_version: '1.3.9'

# ContainerD default directories
containerd_config_dir: '/etc/containerd'
containerd_metadata_dir: '/var/lib/containerd'
containerd_state_dir: '/run/containerd'

# ContainerD default configuration
containerd_default_config: false

# ContainerD configuration
containerd_config:
  debug:
    level: ''
  grpc:
    max_recv_message_size: 16777216
    max_send_message_size: 16777216
  max_container_log_line_size: -1
  registries:
    'docker.io': 'https://registry-1.docker.io'
  systemd_cgroup: true
  default_runtime:
    type: 'io.containerd.runtime.v1.linux'
    engine: ''
    root: ''
  untrusted_workload_runtime:
    type: ''
    engine: ''
    root: ''

# define additional runtimes if necessary, example
# containerd_runtimes:
# - name: ''
#   type: ''
#   engine: ''
#   root: ''
#   privileged_without_host_devices: false
containerd_runtimes: []

containerd_shim_binary: '/usr/bin/containerd-shim'
containerd_runc_binary: '/usr/bin/runc'

# docker-ce apt repo
containerd_repo_base_url: 'https://download.docker.com/linux/{{ ansible_distribution|lower }}'
containerd_repo_gpgkey: '{{ containerd_repo_base_url }}/gpg'
