---
- name: pacman upgrade
  pacman:
    upgrade: yes
    update_cache: yes
  register: pacman_upgrade
  retries: 5
  until: pacman_upgrade is success

- name: install packages
  pacman:
    name: "{{ common_packages }}"
    update_cache: yes
  register: pacman_install_common
  retries: 5
  until: pacman_install_common is success

- name: enable required cgroup features
  lineinfile:
    path: "{{ common_rpi_cmd_file }}"
    state: present
    backrefs: true
    regexp: "^(.*elevator=noop(?<!cgroup_enable=memory cgroup_memory=1))$"
    line: '\1 cgroup_enable=memory cgroup_memory=1'
  notify: reboot hosts
  when: ansible_os_family | lower == 'archlinux'