---
- name: disable swap since kubernetes can't work with swap enabled (1/2)
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: disable swap in /etc/fstab since kubernetes can't work with swap enabled (2/2)
  mount:
    name: '{{ item }}'
    fstype: swap
    state: absent
  loop:
    - swap
    - none

- name: start time services
  service:
    name: systemd-timesyncd
    state: started
    enabled: true

- name: run timedatectl status
  command: /usr/bin/timedatectl show
  changed_when: false
  check_mode: false
  register: timedatectl_result

- name: copy timesyncd config
  copy:
    content: |
      [Time]
      NTP={{ common_ntp_servers | join(' ') }}
      FallbackNTP={{ common_fallback_ntp_servers | join(' ') }}
    dest: /etc/systemd/timesyncd.conf
    mode: 0644

- name: set timezone
  command: "/usr/bin/timedatectl set-timezone {{ common_timezone }}"
  when: common_timezone not in timedatectl_result.stdout_lines[0]

- name: enable ntp
  command: /usr/bin/timedatectl set-ntp true
  when: "'NTP=no' in timedatectl_result.stdout"

- name: 'set hostname'
  hostname:
    name: "{{ inventory_hostname }}"

- name: 'ensure required modules load at system startup'
  ansible.builtin.copy:
    dest: '/etc/modules-load.d/{{ cri_plugin }}.conf'
    content: |
      overlay
      br_netfilter

# Ensure the br_netfilter module is loaded and iptables can see bridged traffic
# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#letting-iptables-see-bridged-traffic
- name: 'ensure required modules are loaded'
  community.general.modprobe:
    name: '{{ item }}'
    state: 'present'
  loop:
    - 'overlay'
    - 'br_netfilter'
  tags:
    - notest

- name: 'ensure sysctl options are configured for container runtime'
  ansible.posix.sysctl:
    name: '{{ item }}'
    value: '1'
    state: 'present'
    sysctl_file: '/etc/sysctl.d/99-kubernetes-cri.conf'
    reload: false
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
    - net.ipv4.ip_forward
  notify: restart systemd-sysctl
