---
- name: apt-get upgrade
  apt:
    upgrade: full
    update_cache: true
    cache_valid_time: 3600
    force_apt_get: true
    autoclean: true
    autoremove: true
  register: apt_upgrade
  retries: 5
  until: apt_upgrade is success
  when: common_upgrade_packages

- name: install common packages
  apt:
    name: '{{ common_packages }}'
    install_recommends: false
    update_cache: true
    cache_valid_time: 3600
    force_apt_get: true
    autoclean: true
    autoremove: true
  register: apt_install_common
  retries: 5
  until: apt_install_common is success

- name: 'add apt key for openshift kubernetes module (1/3)'
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: ADF016E51783213C8A8C831A1348C52605DB2FE6

- name: 'add OBS repo for openshift kubernetes module (2/3)'
  ansible.builtin.apt_repository:
    repo: deb http://download.opensuse.org/repositories/home:/anthr76:/kubernetes/Ubuntu_20.04/ /
    state: present

- name: 'install openshift kubernetes module (3/3)'
  apt:
    name: python-openshift
    update_cache: yes

- name: install and configure log2ram
  include_tasks: log2ram.yml
  when: common_log2ram_enabled
