---
- name: 'manifests | ensure kubernetes manifests directory "{{ cluster_kubernetes_manifests_path }}" exists'
  ansible.builtin.file:
    path: '{{ cluster_kubernetes_manifests_path }}'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: 0700

- name: 'manifests | ensure haproxy config directory "{{ haproxy_config_dir }}" exists'
  ansible.builtin.file:
    path: '{{ haproxy_config_dir }}'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: 0700

- name: 'manifests | ensure haproxy configuration file is up to date'
  ansible.builtin.template:
    src: 'haproxy.cfg.j2'
    dest: '{{ haproxy_config_dir }}/haproxy.cfg'
    owner: 'root'
    group: 'root'
    mode: 0644
    backup: true

- name: 'manifests | get current checksum of haproxy config file'
  ansible.builtin.stat:
    path: '{{ haproxy_config_dir }}/haproxy.cfg'
    get_attributes: false
    get_checksum: true
    get_mime: false
  register: haproxy_config_stat

- name: 'manifests | write haproxy static pod manifest'
  ansible.builtin.template:
    src: 'haproxy.yaml.j2'
    dest: '{{ cluster_kubernetes_manifests_path }}/haproxy.yaml'
    owner: 'root'
    group: 'root'
    mode: 0644
