---
common_packages: []
common_rpi_cmd_file: /boot/firmware/cmdline.txt # For kernel arguments
common_rpi_config_file: /boot/firmware/syscfg.txt # For RPi configuration
common_rpi_gpu_memory: 16 # https://www.raspberrypi.org/documentation/configuration/config-txt/memory.md
common_rpi_overclock: false # https://www.raspberrypi.org/documentation/configuration/config-txt/overclocking.md
common_rpi_overvoltage: 6 # See above mentioned docs
common_rpi_arm_frequency: 2000 # CPU Frequency in MHz
common_reboot_handler_enabled: true # Set to false to not reboot after changes
