---
####
# Role - cluster
####
# cluster_name: kubernetes
# cluster_extra_sans:
#  - "{{ keepalived_vip }}"
# cluster_control_plane_endpoint: "{{ keepalived_vip }}:8443"
# cluster_enable_admission_plugins: "NodeRestriction"
# cluster_authorization_mode: "Node,RBAC"
# cluster_audit_log_path: "/var/log/kubernetes/audit.log"
# cluster_audit_log_maxage: 30
# cluster_audit_log_maxbackup: 10
# cluster_audit_log_maxsize: 100
# cluster_pod_subnet: ""
cluster_kube_proxy_enabled: false
cluster_etcd_heartbeat_interval: 250
cluster_etcd_election_timeout: 1250
cluster_etcd_snapshot_count: 5000

####
# Role - cni
####
cni_plugin: cilium

####
# Role - cloudflared
# Cloudflare options for exposing Kubernetes services via HTTPS/SSH
####
# cloudflared_enabled: false
# cloudflared_kube_api_server_dns: ''
# cloudflared_version: 2021.2.5
