# main.yml - use dependency management to select the proper container runtime
---

dependencies:
- role: container-runtime/containerd
  when:
  - cri_plugin == 'containerd'

- role: container-runtime/docker
  when:
  - cri_plugin == 'docker'
