---
- name: Reset Kubernetes Instance (1/2)
  become: true
  command: kubeadm reset -f
  register: kubeadm_reset

- name: Cleanup /etc/cni/net.d file (2/2)
  become: true
  file:
    path: /etc/cni/net.d
    state: absent
