---
# 2 GiB or more of RAM per machine--any less leaves little room for your apps.
# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#before-you-begin
- name: 'validate control-plane memory requirement'
  assert:
    that:
        - ansible_memtotal_mb >= 2000
    fail_msg:
      - "2 GiB or more of RAM per machine required for control-planes nodes"

# At least 2 CPUs on the machine that you use as a control-plane node.
# # https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#before-you-begin
- name: 'validate control-plane CPU requirement'
  assert:
    that:
        - ansible_processor_count >= 2
    fail_msg:
      - "At least 2 CPUs on the machine that you use as a control-plane node."
