---
- hosts: masters
  become: true

  vars_files:
    - ../vars.yml

  roles:
    - ../roles/keepalived
    - ../roles/haproxy
    - ../roles/kubernetes
    - ../roles/masters
    - {
        role: ../roles/initial-master,
        when: "groups['masters'][0] == inventory_hostname",
      }
    - { role: ../roles/cni, when: "groups['masters'][0] == inventory_hostname" }
    - {
        role: ../roles/other-masters,
        when: "groups['masters'][0] != inventory_hostname",
      }
