---
- name: Register master join command
  changed_when: false
  delegate_to: localhost
  command: cat output/k8s-master-join-command
  register: k8s_master_join
  vars:
    ansible_become: false

- name: Execute master kubeadm join
  command: "{{ k8s_master_join.stdout }}"
  args:
    creates: /etc/kubernetes/kubelet.conf
