---

#- name: Install Helm v3
#  shell: |
#    set -o pipefail && curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
#  args:
#    warn: false

- name: Add Cilium Helm Repo
  command:
    cmd: helm repo add cilium https://helm.cilium.io/
    creates: /usr/local/bin/helm

- name: Generate cilium helm values
  template:
    src: values.yaml.j2
    dest: /root/values.yaml
    mode: 0644

- name: Deploy Cilium
  shell: |
    set -o pipefail && helm upgrade -i cilium cilium/cilium \
    --values=/root/values.yaml \
    --version {{ cni_cilium_helm_version }} \
    --namespace kube-system
  args:
    creates: /etc/cni/net.d/05-cilium.conf

# TODO: Only deploy kube-router if enabled
- name: Create Manifests Directory
  file:
    path: /root/manifests
    state: directory
    mode: 0700

- name: "Generate kube-router manifests"
  become: true
  template:
    src: "{{ item }}"
    dest: "/root/manifests/{{ item | basename | replace('.j2','') }}"
    mode: 0600
  with_items:
  - "generic-kuberouter-only-advertise-routes.yaml.j2"

- name: Apply kube-router manifests
  command:
    cmd: "kubectl apply -f /root/manifests/{{ item }}"
  with_items:
  - "generic-kuberouter-only-advertise-routes.yaml"

- name: Remove Manifests Directory
  file:
    path: /root/manifests
    state: absent
