---
- name: applying cilium
  command:
    cmd: kubectl apply -f https://raw.githubusercontent.com/cilium/cilium/v1.9/install/kubernetes/quick-install.yaml
    creates: /etc/cni/net.d/10-cilium.conflist
