---

- name: Debug 1
  ansible.builtin.debug:
    var: cluster_control_plane_endpoint
- name: Debug 2
  ansible.builtin.debug:
    var: cluster_control_plane_endpoint | urlsplit('hostname')
- name: Debug 3
  ansible.builtin.debug:
    var: cluster_control_plane_endpoint | urlsplit('port')

- name: Generate cilium helm values
  template:
    src: values.yaml.j2
    dest: /root/values.yaml
    mode: 0644

- name: Add Cilium Helm Repo
  community.kubernetes.helm_repository:
    name: cilium
    repo_url: "https://helm.cilium.io/"
  delegate_to: "localhost"

- name: Deploy Cilium
  community.kubernetes.helm:
    name: cilium
    chart_ref: cilium/cilium
    release_namespace: kube-system
    chart_version: "{{ cni_cilium_helm_version }}"
    values: "{{ lookup('template', 'values.yaml.j2') | from_yaml }}"
  delegate_to: "localhost"

- name: Apply kube-router manifests
  community.kubernetes.k8s:
    state: present
    template: 'generic-kuberouter-only-advertise-routes.yaml.j2'
  when:
    - cluster_kube_proxy == "disabled"
  delegate_to: "localhost"
