---
- name: preflight checks
  import_tasks: pre_checks.yml
  run_once: true

# Instructions: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#pod-network
- name: 'setup {{ cni_plugin }} container network interface (cni)'
  import_tasks: '{{ cni_plugin }}.yml'
  when: inventory_hostname == cluster_main_master
