---
- name: kubeadm init
  command: kubeadm init --token-ttl=0

- name: apply weave CNI
  command: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
