---
- hosts: all
  become: true
  gather_facts: true

  vars_files:
    - ./vars.yml

  tasks:
    - include_role:
        name: common
      tags: ['common']
    # - name: 'rebooting hosts'
    #   reboot:
    #     msg: 'Pis are being rebooted'
    #     reboot_timeout: 60
    #   ignore_errors: true
# - hosts: worker
#   roles:
#     - worker

# - hosts: master
#   roles:
#     - master
