---
- hosts: all
  become: true
  gather_facts: true

  vars_files:
    - ./vars.yml

  tasks:
    - include_role:
        name: common
      tags: ['common']
    - include_role:
        name: worker
      tags: ['worker']
    # - name: 'rebooting hosts'
    #   reboot:
    #     msg: 'Pis are being rebooted'
    #     reboot_timeout: 60
    #   ignore_errors: true
