---
- name: Register worker join command
  changed_when: false
  delegate_to: localhost
  command: cat output/k8s-worker-join-command
  register: k8s_worker_join
  run_once: true
  vars:
    ansible_become: false

- name: Execute worker kubeadm join
  command: "{{ k8s_worker_join.stdout }}"
  args:
    creates: /etc/kubernetes/kubelet.conf
