name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Shellcheck
        uses: azohra/shell-linter@v0.2.0
        with:
          path: "raspbernetes"

      - name: Lint yaml
        uses: karancode/yamllint-github-action@v1.0.0
        with:
          yamllint_file_or_dir: "./ansible"
          yamllint_config_filepath: "./ansible/.yamllint"

      - name: Lint Ansible
        uses: ansible/ansible-lint-action@master
        with:
          targets: "./ansible/playbooks/*.yml"
          args: '--exclude ./ansible/handlers -c ./ansible/.ansible-lint'

      - name: Validate Cloud-Config
        run: |
          sudo apt-get update -y
          sudo apt-get install -y cloud-init
          cloud-init devel schema --config-file ./setup/cloud-config.yml
