name: terraform

on: push

jobs:
  tflint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: tflint
        uses: reviewdog/action-tflint@master
        with:
          github_token: ${{ secrets.github_token }}
          working_directory: 'infrastructure/gcp' # Optional. Change working directory
          reporter: github-pr-review # Optional. Change reporter
          fail_on_error: 'true' # Optional. Fail action if errors are found
          filter_mode: 'nofilter' # Optional. Check all files, not just the diff
