name: terraform

on: push

jobs:
  tflint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      # Install latest Terraform manually as Docker-based GitHub Actions are slow due to lack of caching
      # Note: Terraform is not needed for tflint
      - name: Install Terraform
        run: |
          brew install terraform

      # Run init to get module code to be able to use `--module`
      - name: Terraform init
        working-directory: infrastructure/gcp
        run: |
          terraform init

      - name: tflint
        uses: reviewdog/action-tflint@master
        with:
          github_token: ${{ secrets.github_token }}
          working_directory: 'infrastructure/gcp' # Optional. Change working directory
          reporter: github-pr-review # Optional. Change reporter
          fail_on_error: 'true' # Optional. Fail action if errors are found
          filter_mode: 'nofilter' # Optional. Check all files, not just the diff
          flags: '--module' # Optional. Add custom tflint flags
